#com.didispace.blog.name=程序猿DD
#com.didispace.blog.title=Spring Boot教程

#server.port=8888
com:
  didispace:
    blog:
      name: 程序猿DD
      title: Spring Boot教程


server:
    port: 8888


#spring:
#  datasource:
#    url: jdbc:mysql://localhost:3306/mmmai
#    username: root
#    password: 201017
#    driver-class-name: com.mysql.jdbc.Driver