#com.didispace.blog.name=程序猿DD
#com.didispace.blog.title=Spring Boot教程

#server.port=8888
com:
  didispace:
    blog:
      name: 程序猿DD
      title: Spring Boot教程


server:
    port: 8888
    context-path: /sell


spring:
  datasource:
    url: jdbc:mysql://192.168.40.199:3306/sell?characterEncoding=UTF-8
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    database: Mysql
    showSql: true
    hibernate:
        ddl-auto: update
        naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
        properties:
          hibernate:
            dialect: org.hibernate.dialect.MySQL5Dialect


logging:
  pattern:
    console: "%d - %msg%n"
  level: info
  file: E:\LogTest\sell\info.[%d].log
